-- Biblioteca de sonidos del Cooldown Manager de WoW Midnight (Blizzard_CooldownViewer).
-- Cada entrada: soundKitID, clave de texto localizado del juego y nombre de respaldo.

local _, ns = ...

ns.SoundLibrary = {
    { category = "Animals", sounds = {
        { id = 316401, key = "CDMSND_ANIMALS_CAT", name = "Cat" },
        { id = 316406, key = "CDMSND_ANIMALS_CHICKEN", name = "Chicken" },
        { id = 316407, key = "CDMSND_ANIMALS_COW", name = "Cow" },
        { id = 316409, key = "CDMSND_ANIMALS_GNOLL", name = "Gnoll" },
        { id = 316715, key = "CDMSND_ANIMALS_GOAT", name = "Goat" },
        { id = 316411, key = "CDMSND_ANIMALS_LION", name = "Lion" },
        { id = 316412, key = "CDMSND_ANIMALS_PANTHER", name = "Panther" },
        { id = 316413, key = "CDMSND_ANIMALS_RATTLESNAKE", name = "Rattlesnake" },
        { id = 316414, key = "CDMSND_ANIMALS_SHEEP", name = "Sheep" },
        { id = 316415, key = "CDMSND_ANIMALS_WOLF", name = "Wolf" },
    } },
    { category = "Devices", sounds = {
        { id = 316442, key = "CDMSND_DEVICES_BOAT_HORN", name = "Boat Horn" },
        { id = 316436, key = "CDMSND_DEVICES_AIR_HORN", name = "Air Horn" },
        { id = 316713, key = "CDMSND_DEVICES_BIKE_HORN", name = "Bike Horn" },
        { id = 316446, key = "CDMSND_DEVICES_CASH_REGISTER", name = "Cash Register" },
        { id = 316717, key = "CDMSND_DEVICES_JACKPOT_BELL", name = "Jackpot Bell" },
        { id = 316718, key = "CDMSND_DEVICES_JACKPOT_COINS", name = "Jackpot Coins" },
        { id = 316719, key = "CDMSND_DEVICES_JACKPOT_FAIL", name = "Jackpot Fail" },
        { id = 316433, key = "CDMSND_DEVICES_ROTARY_PHONE_DIAL", name = "Rotary Phone Dial" },
        { id = 316492, key = "CDMSND_DEVICES_ROTARY_PHONE_RING", name = "Rotary Phone Ring" },
        { id = 316425, key = "CDMSND_DEVICES_STOVE_PIPE", name = "Stove Pipe" },
        { id = 316430, key = "CDMSND_DEVICES_TRASHCAN_LID", name = "Trashcan Lid" },
    } },
    { category = "Impacts", sounds = {
        { id = 316528, key = "CDMSND_IMPACTS_ANVIL_STRIKE", name = "Anvil Strike" },
        { id = 316419, key = "CDMSND_IMPACTS_BUBBLE_SMASH", name = "Bubble Smash" },
        { id = 316531, key = "CDMSND_IMPACTS_LOW_THUD", name = "Low Thud" },
        { id = 316532, key = "CDMSND_IMPACTS_METAL_CLANKS", name = "Metal Clanks" },
        { id = 316486, key = "CDMSND_IMPACTS_METAL_RATTLE", name = "Metal Rattle" },
        { id = 316484, key = "CDMSND_IMPACTS_METAL_SCRAPE", name = "Metal Scrape" },
        { id = 316536, key = "CDMSND_IMPACTS_METAL_WARBLE", name = "Metal Warble" },
        { id = 316434, key = "CDMSND_IMPACTS_POP_CLICK", name = "Pop Click" },
        { id = 316453, key = "CDMSND_IMPACTS_STRANGE_CLANG", name = "Strange Clang" },
        { id = 316535, key = "CDMSND_IMPACTS_SWORD_SCRAPE", name = "Sword Scrape" },
    } },
    { category = "Instruments", sounds = {
        { id = 316493, key = "CDMSND_INSTRUMENTS_BELL_RING", name = "Bell Ring" },
        { id = 316712, key = "CDMSND_INSTRUMENTS_BELL_TRILL", name = "Bell Trill" },
        { id = 316722, key = "CDMSND_INSTRUMENTS_BRASS", name = "Brass" },
        { id = 316447, key = "CDMSND_INSTRUMENTS_CHIME_ASCENDING", name = "Chime Ascending" },
        { id = 316477, key = "CDMSND_INSTRUMENTS_GUITAR_CHUG", name = "Guitar Chug" },
        { id = 316482, key = "CDMSND_INSTRUMENTS_GUITAR_PINCH", name = "Guitar Pinch" },
        { id = 316509, key = "CDMSND_INSTRUMENTS_PITCH_PIPE_DISTRESSED", name = "Pitch Pipe Distressed" },
        { id = 316501, key = "CDMSND_INSTRUMENTS_PITCH_PIPE_NOTE", name = "Pitch Pipe Note" },
        { id = 316540, key = "CDMSND_INSTRUMENTS_SYNTH_BIG", name = "Synth Big" },
        { id = 316476, key = "CDMSND_INSTRUMENTS_SYNTH_BUZZ", name = "Synth Buzz" },
        { id = 316460, key = "CDMSND_INSTRUMENTS_SYNTH_HIGH", name = "Synth High" },
        { id = 316723, key = "CDMSND_INSTRUMENTS_WARHORN", name = "Warhorn" },
    } },
    { category = "Short", sounds = {
        { id = 353392, key = "CDMSND_SHORT_BELL_STRIKE", name = "Bell Strike" },
        { id = 353387, key = "CDMSND_SHORT_BELL_TREE", name = "Bell Tree" },
        { id = 353388, key = "CDMSND_SHORT_BIG_POT", name = "Big Pot" },
        { id = 353389, key = "CDMSND_SHORT_BLADES", name = "Blades" },
        { id = 353424, key = "CDMSND_SHORT_COFFEE_MUG", name = "Coffee Mug" },
        { id = 353393, key = "CDMSND_SHORT_COW_BELL", name = "Cow Bell" },
        { id = 353395, key = "CDMSND_SHORT_FINGER_SNAP", name = "Finger Snap" },
        { id = 353404, key = "CDMSND_SHORT_GUITAR", name = "Guiter" },
        { id = 353405, key = "CDMSND_SHORT_KALIMBA", name = "Kalimba" },
        { id = 353406, key = "CDMSND_SHORT_METAL_BLADE_DROP", name = "Metal Blade Drop" },
        { id = 353407, key = "CDMSND_SHORT_METAL_BLADE_ON_ROD", name = "Metal Blade On Rod" },
        { id = 353408, key = "CDMSND_SHORT_METAL_IMPACT", name = "Metal Impact" },
        { id = 353410, key = "CDMSND_SHORT_MINI_WOOD_XYLOPHONE", name = "Mini Wood Xylophone" },
        { id = 353425, key = "CDMSND_SHORT_PAPER_CUP", name = "Paper Cup" },
        { id = 353417, key = "CDMSND_SHORT_SHEET_METAL", name = "Sheet Metal" },
        { id = 353419, key = "CDMSND_SHORT_STOVE_PIPE", name = "Stove Pipe" },
        { id = 353420, key = "CDMSND_SHORT_STOVE_PIPE_BLADE", name = "Stove Pipe Blade" },
        { id = 353421, key = "CDMSND_SHORT_SWORD_SHING", name = "Sword Shing" },
        { id = 353402, key = "CDMSND_SHORT_SYNTH_BLEEP", name = "Synth Bleep" },
        { id = 353400, key = "CDMSND_SHORT_SYNTH_BLURP", name = "Synth Blurp" },
        { id = 353397, key = "CDMSND_SHORT_SYNTH_ERROR", name = "Synth Error" },
        { id = 353399, key = "CDMSND_SHORT_SYNTH_HIGH", name = "Synth High" },
        { id = 353423, key = "CDMSND_SHORT_TRIANGLE", name = "Triangle" },
        { id = 353426, key = "CDMSND_SHORT_WATER_DROP", name = "Water Drop" },
        { id = 353427, key = "CDMSND_SHORT_WINE_BOTTLE", name = "Wine Bottle" },
        { id = 353428, key = "CDMSND_SHORT_WOOD_XYLOPHONE", name = "Wood Xylophone" },
    } },
    { category = "Warcraft II", sounds = {
        { id = 316731, key = "CDMSND_WAR2_ABSTRACT_WHOOSH", name = "Abstract Whoosh" },
        { id = 316733, key = "CDMSND_WAR2_CHOIR", name = "Choir" },
        { id = 316735, key = "CDMSND_WAR2_CONSTRUCTION", name = "Construction" },
        { id = 316736, key = "CDMSND_WAR2_MAGIC_CHIMES", name = "Magic Chimes" },
        { id = 316745, key = "CDMSND_WAR2_PIG_SQUEAL", name = "Pig Squeal" },
        { id = 316738, key = "CDMSND_WAR2_SAWS", name = "Saws" },
        { id = 316746, key = "CDMSND_WAR2_SEAL", name = "Seal" },
        { id = 316748, key = "CDMSND_WAR2_SLOW", name = "Slow" },
        { id = 316749, key = "CDMSND_WAR2_SMITH", name = "Smith" },
        { id = 316739, key = "CDMSND_WAR2_SYNTH_STINGER", name = "Synth Stinger" },
        { id = 316740, key = "CDMSND_WAR2_TRUMPET_RALLY", name = "Trumpet Rally" },
        { id = 316737, key = "CDMSND_WAR2_ZIPPY_MAGIC", name = "Zippy Magic" },
    } },
    { category = "Warcraft III", sounds = {
        { id = 316773, key = "CDMSND_WAR3_BELL", name = "Bell" },
        { id = 316774, key = "CDMSND_WAR3_CRUNCHY_BELL", name = "Crunchy Bell" },
        { id = 316768, key = "CDMSND_WAR3_DRUM_SPLASH", name = "Drum Splash" },
        { id = 316775, key = "CDMSND_WAR3_ERROR", name = "Error" },
        { id = 316769, key = "CDMSND_WAR3_FANFARE", name = "Fanfare" },
        { id = 316776, key = "CDMSND_WAR3_GATE_OPEN", name = "Gate Open" },
        { id = 316770, key = "CDMSND_WAR3_GOLD", name = "Gold" },
        { id = 316778, key = "CDMSND_WAR3_MAGIC_SHIMMER", name = "Magic Shimmer" },
        { id = 316771, key = "CDMSND_WAR3_RINGOUT", name = "Ringout" },
        { id = 316765, key = "CDMSND_WAR3_ROOSTER", name = "Rooster" },
        { id = 316779, key = "CDMSND_WAR3_SHIMMER_BELL", name = "Shimmer Bell" },
        { id = 316766, key = "CDMSND_WAR3_WOLF_HOWL", name = "Wolf Howl" },
    } },
}
